export interface IClient {
  id: string;
  first_name: string;
  last_name: string;
  age: string;
  gender: string;
  car: string;
}

export const clients: IClient[] = [
  {
    id: '1',
    first_name: 'Barnaby',
    last_name: 'Diggins',
    age: '19',
    gender: 'Male',
    car: 'GMC',
  },
  {
    id: '2',
    first_name: 'Christi',
    last_name: 'Sandyford',
    age: '18',
    gender: 'Polygender',
    car: 'Lamborghini',
  },
  {
    id: '3',
    first_name: 'Clarinda',
    last_name: 'Minshull',
    age: '18',
    gender: 'Female',
    car: 'Jeep',
  },
  {
    id: '4',
    first_name: 'Bronnie',
    last_name: 'Fanton',
    age: '17',
    gender: 'Female',
    car: 'Audi',
  },
  {
    id: '5',
    first_name: 'Gayleen',
    last_name: 'Rimbault',
    age: '20',
    gender: 'Male',
    car: 'Chevrolet',
  },
  {
    id: '6',
    first_name: 'Wes',
    last_name: 'Skeene',
    age: '20',
    gender: 'Female',
    car: 'Mercury',
  },
  {
    id: '7',
    first_name: 'Courtnay',
    last_name: 'Donnel',
    age: '21',
    gender: 'Female',
    car: 'Nissan',
  },
  {
    id: '8',
    first_name: 'Andra',
    last_name: 'Elphinstone',
    age: '21',
    gender: 'Male',
    car: 'Ford',
  },
  {
    id: '9',
    first_name: 'Beulah',
    last_name: 'Gummie',
    age: '21',
    gender: 'Female',
    car: 'GMC',
  },
  {
    id: '10',
    first_name: 'Bibbye',
    last_name: 'Sarre',
    age: '21',
    gender: 'Female',
    car: 'Saturn',
  },
  {
    id: '11',
    first_name: 'Lucien',
    last_name: 'Parmenter',
    age: '18',
    gender: 'Female',
    car: 'Chrysler',
  },
  {
    id: '12',
    first_name: 'Clare',
    last_name: 'Kluger',
    age: '18',
    gender: 'Male',
    car: 'Jaguar',
  },
  {
    id: '13',
    first_name: 'Ruth',
    last_name: 'Karlsson',
    age: '19',
    gender: 'Male',
    car: 'Jaguar',
  },
  {
    id: '14',
    first_name: 'Adina',
    last_name: 'Avrasin',
    age: '18',
    gender: 'Male',
    car: 'Ford',
  },
  {
    id: '15',
    first_name: 'Mary',
    last_name: 'Peatheyjohns',
    age: '17',
    gender: 'Agender',
    car: 'Dodge',
  },
  {
    id: '16',
    first_name: 'Patrizia',
    last_name: 'Wolland',
    age: '19',
    gender: 'Male',
    car: 'Volvo',
  },
  {
    id: '17',
    first_name: 'Perla',
    last_name: 'Sand',
    age: '20',
    gender: 'Female',
    car: 'Lincoln',
  },
  {
    id: '18',
    first_name: 'Tannie',
    last_name: 'McShirie',
    age: '19',
    gender: 'Male',
    car: 'Subaru',
  },
  {
    id: '19',
    first_name: 'Armstrong',
    last_name: 'Heningham',
    age: '18',
    gender: 'Bigender',
    car: 'Volvo',
  },
  {
    id: '20',
    first_name: 'Cary',
    last_name: 'Blenkiron',
    age: '17',
    gender: 'Non-binary',
    car: 'Mercury',
  },
  {
    id: '21',
    first_name: 'Berthe',
    last_name: 'Deguara',
    age: '21',
    gender: 'Female',
    car: 'Pontiac',
  },
  {
    id: '22',
    first_name: 'Ruthe',
    last_name: 'Mattisson',
    age: '19',
    gender: 'Male',
    car: 'Infiniti',
  },
  {
    id: '23',
    first_name: 'Federico',
    last_name: 'Mold',
    age: '19',
    gender: 'Male',
    car: 'Chevrolet',
  },
  {
    id: '24',
    first_name: 'Kelcie',
    last_name: 'Andriesse',
    age: '18',
    gender: 'Male',
    car: 'GMC',
  },
  {
    id: '25',
    first_name: 'Leone',
    last_name: 'Dennes',
    age: '20',
    gender: 'Male',
    car: 'Land Rover',
  },
  {
    id: '26',
    first_name: 'Chet',
    last_name: 'Viscovi',
    age: '21',
    gender: 'Male',
    car: 'Dodge',
  },
  {
    id: '27',
    first_name: 'Kerwin',
    last_name: 'Sandcroft',
    age: '18',
    gender: 'Male',
    car: 'Chevrolet',
  },
  {
    id: '28',
    first_name: 'Neila',
    last_name: 'Matisoff',
    age: '19',
    gender: 'Female',
    car: 'Maserati',
  },
  {
    id: '29',
    first_name: 'Dee dee',
    last_name: 'Baroc',
    age: '20',
    gender: 'Female',
    car: 'Land Rover',
  },
  {
    id: '30',
    first_name: 'Giselbert',
    last_name: 'Fife',
    age: '17',
    gender: 'Female',
    car: 'Saab',
  },
  {
    id: '31',
    first_name: 'Ardeen',
    last_name: 'Gethins',
    age: '19',
    gender: 'Male',
    car: 'Saab',
  },
  {
    id: '32',
    first_name: 'Kania',
    last_name: 'Gavin',
    age: '17',
    gender: 'Male',
    car: 'Ford',
  },
  {
    id: '33',
    first_name: 'Xavier',
    last_name: 'Cadore',
    age: '18',
    gender: 'Female',
    car: 'GMC',
  },
  {
    id: '34',
    first_name: 'Allister',
    last_name: 'Campey',
    age: '21',
    gender: 'Male',
    car: 'Hummer',
  },
  {
    id: '35',
    first_name: 'Orelie',
    last_name: 'Winckles',
    age: '17',
    gender: 'Female',
    car: 'Mazda',
  },
  {
    id: '36',
    first_name: 'Candide',
    last_name: 'Tonge',
    age: '18',
    gender: 'Male',
    car: 'Hyundai',
  },
  {
    id: '37',
    first_name: 'Modesta',
    last_name: 'Pedro',
    age: '19',
    gender: 'Bigender',
    car: 'Fiat',
  },
  {
    id: '38',
    first_name: 'Bale',
    last_name: 'Bosenworth',
    age: '21',
    gender: 'Male',
    car: 'Ford',
  },
  {
    id: '39',
    first_name: 'Moses',
    last_name: 'Garvan',
    age: '20',
    gender: 'Female',
    car: 'Toyota',
  },
  {
    id: '40',
    first_name: 'Greg',
    last_name: 'Francis',
    age: '18',
    gender: 'Female',
    car: 'Nissan',
  },
  {
    id: '41',
    first_name: 'Ethe',
    last_name: 'Danser',
    age: '21',
    gender: 'Female',
    car: 'Ford',
  },
  {
    id: '42',
    first_name: 'Giraud',
    last_name: 'Bowlands',
    age: '21',
    gender: 'Male',
    car: 'Mazda',
  },
  {
    id: '43',
    first_name: 'Christean',
    last_name: 'Lurriman',
    age: '18',
    gender: 'Female',
    car: 'Chrysler',
  },
  {
    id: '44',
    first_name: 'Alverta',
    last_name: 'Jeroch',
    age: '18',
    gender: 'Female',
    car: 'Mercedes-Benz',
  },
  {
    id: '45',
    first_name: 'Jennine',
    last_name: 'Garvie',
    age: '18',
    gender: 'Female',
    car: 'Mercedes-Benz',
  },
  {
    id: '46',
    first_name: 'Claudius',
    last_name: 'Rooksby',
    age: '17',
    gender: 'Female',
    car: 'Nissan',
  },
  {
    id: '47',
    first_name: 'Fanni',
    last_name: 'Worland',
    age: '17',
    gender: 'Male',
    car: 'BMW',
  },
  {
    id: '48',
    first_name: 'Georgena',
    last_name: 'McFetrich',
    age: '19',
    gender: 'Female',
    car: 'Lexus',
  },
  {
    id: '49',
    first_name: 'Arv',
    last_name: 'Coggell',
    age: '21',
    gender: 'Female',
    car: 'Dodge',
  },
  {
    id: '50',
    first_name: 'Stephani',
    last_name: 'De Hooge',
    age: '21',
    gender: 'Female',
    car: 'Jeep',
  },
  {
    id: '51',
    first_name: 'Amble',
    last_name: 'Semon',
    age: '18',
    gender: 'Female',
    car: 'Volvo',
  },
  {
    id: '52',
    first_name: 'Polly',
    last_name: 'Brouard',
    age: '19',
    gender: 'Male',
    car: 'BMW',
  },
  {
    id: '53',
    first_name: 'Rowen',
    last_name: 'Morcomb',
    age: '19',
    gender: 'Female',
    car: 'Buick',
  },
  {
    id: '54',
    first_name: 'Ynes',
    last_name: 'Armit',
    age: '20',
    gender: 'Male',
    car: 'Audi',
  },
  {
    id: '55',
    first_name: 'Mattias',
    last_name: 'Baitey',
    age: '18',
    gender: 'Female',
    car: 'Land Rover',
  },
  {
    id: '56',
    first_name: 'Nellie',
    last_name: 'Brugemann',
    age: '20',
    gender: 'Female',
    car: 'Chrysler',
  },
  {
    id: '57',
    first_name: 'Colene',
    last_name: 'Shury',
    age: '21',
    gender: 'Male',
    car: 'Dodge',
  },
  {
    id: '58',
    first_name: 'Carny',
    last_name: 'Valentinuzzi',
    age: '18',
    gender: 'Female',
    car: 'Buick',
  },
  {
    id: '59',
    first_name: 'Salomon',
    last_name: 'Willment',
    age: '17',
    gender: 'Male',
    car: 'GMC',
  },
  {
    id: '60',
    first_name: 'Ode',
    last_name: 'Gianinotti',
    age: '20',
    gender: 'Female',
    car: 'Chevrolet',
  },
  {
    id: '61',
    first_name: 'Leland',
    last_name: 'Marchi',
    age: '18',
    gender: 'Male',
    car: 'Infiniti',
  },
  {
    id: '62',
    first_name: 'Hendrik',
    last_name: 'Renne',
    age: '19',
    gender: 'Female',
    car: 'Mitsubishi',
  },
  {
    id: '63',
    first_name: 'Koren',
    last_name: 'Reuss',
    age: '18',
    gender: 'Female',
    car: 'Dodge',
  },
  {
    id: '64',
    first_name: 'Margeaux',
    last_name: 'Rolland',
    age: '20',
    gender: 'Male',
    car: 'Saab',
  },
  {
    id: '65',
    first_name: 'Julee',
    last_name: 'Garred',
    age: '20',
    gender: 'Male',
    car: 'Jaguar',
  },
  {
    id: '66',
    first_name: 'Bordie',
    last_name: 'Elverstone',
    age: '18',
    gender: 'Bigender',
    car: 'Ford',
  },
  {
    id: '67',
    first_name: 'Aubine',
    last_name: 'Eskrick',
    age: '17',
    gender: 'Male',
    car: 'Pontiac',
  },
  {
    id: '68',
    first_name: 'Saleem',
    last_name: 'Kienlein',
    age: '17',
    gender: 'Female',
    car: 'Mercedes-Benz',
  },
  {
    id: '69',
    first_name: 'Zachery',
    last_name: 'Muncaster',
    age: '21',
    gender: 'Male',
    car: 'Dodge',
  },
  {
    id: '70',
    first_name: 'Billy',
    last_name: 'Whilder',
    age: '17',
    gender: 'Male',
    car: 'Cadillac',
  },
  {
    id: '71',
    first_name: 'Dan',
    last_name: 'Rousby',
    age: '21',
    gender: 'Female',
    car: 'Saab',
  },
  {
    id: '72',
    first_name: 'Jourdain',
    last_name: 'Harris',
    age: '20',
    gender: 'Male',
    car: 'BMW',
  },
  {
    id: '73',
    first_name: 'Barron',
    last_name: 'Scothorn',
    age: '18',
    gender: 'Female',
    car: 'Toyota',
  },
  {
    id: '74',
    first_name: 'Ebenezer',
    last_name: "D'Aubney",
    age: '20',
    gender: 'Male',
    car: 'Volkswagen',
  },
  {
    id: '75',
    first_name: 'Reinaldo',
    last_name: 'Sinisbury',
    age: '21',
    gender: 'Female',
    car: 'Nissan',
  },
  {
    id: '76',
    first_name: 'Giraldo',
    last_name: 'Nutbrown',
    age: '18',
    gender: 'Female',
    car: 'Audi',
  },
  {
    id: '77',
    first_name: 'Klarrisa',
    last_name: 'Abell',
    age: '21',
    gender: 'Male',
    car: 'Nissan',
  },
  {
    id: '78',
    first_name: 'Hana',
    last_name: 'Norcock',
    age: '21',
    gender: 'Male',
    car: 'Toyota',
  },
  {
    id: '79',
    first_name: 'Kordula',
    last_name: 'Moxley',
    age: '17',
    gender: 'Female',
    car: 'Buick',
  },
  {
    id: '80',
    first_name: 'Kath',
    last_name: 'Davers',
    age: '21',
    gender: 'Male',
    car: 'Ford',
  },
  {
    id: '81',
    first_name: 'Barry',
    last_name: 'Pennyman',
    age: '21',
    gender: 'Male',
    car: 'Oldsmobile',
  },
  {
    id: '82',
    first_name: 'Alleyn',
    last_name: 'Bercevelo',
    age: '21',
    gender: 'Female',
    car: 'Chevrolet',
  },
  {
    id: '83',
    first_name: 'Bobby',
    last_name: 'Smorfit',
    age: '21',
    gender: 'Male',
    car: 'Chevrolet',
  },
  {
    id: '84',
    first_name: 'Lothario',
    last_name: 'Allday',
    age: '17',
    gender: 'Female',
    car: 'Ford',
  },
  {
    id: '85',
    first_name: 'Konstantine',
    last_name: 'Heims',
    age: '20',
    gender: 'Genderfluid',
    car: 'Ford',
  },
  {
    id: '86',
    first_name: 'Netty',
    last_name: 'Hillatt',
    age: '18',
    gender: 'Female',
    car: 'Dodge',
  },
  {
    id: '87',
    first_name: 'Kayle',
    last_name: 'Sisselot',
    age: '21',
    gender: 'Male',
    car: 'GMC',
  },
  {
    id: '88',
    first_name: 'Nikkie',
    last_name: 'Abramsky',
    age: '18',
    gender: 'Female',
    car: 'Audi',
  },
  {
    id: '89',
    first_name: 'Welbie',
    last_name: 'Gudgin',
    age: '21',
    gender: 'Male',
    car: 'Mercedes-Benz',
  },
  {
    id: '90',
    first_name: 'Kitti',
    last_name: 'Lodin',
    age: '20',
    gender: 'Polygender',
    car: 'GMC',
  },
  {
    id: '91',
    first_name: 'Billy',
    last_name: 'Doldon',
    age: '19',
    gender: 'Non-binary',
    car: 'Ford',
  },
  {
    id: '92',
    first_name: 'Rachael',
    last_name: 'Bawden',
    age: '19',
    gender: 'Bigender',
    car: 'Ford',
  },
  {
    id: '93',
    first_name: 'Danika',
    last_name: 'Schouthede',
    age: '17',
    gender: 'Male',
    car: 'Nissan',
  },
  {
    id: '94',
    first_name: 'Arni',
    last_name: 'Evelyn',
    age: '21',
    gender: 'Female',
    car: 'Scion',
  },
  {
    id: '95',
    first_name: 'Theressa',
    last_name: 'Hendrich',
    age: '21',
    gender: 'Female',
    car: 'Chevrolet',
  },
  {
    id: '96',
    first_name: 'Antonella',
    last_name: 'Selvey',
    age: '19',
    gender: 'Male',
    car: 'Ford',
  },
  {
    id: '97',
    first_name: 'Leshia',
    last_name: 'Ellingsworth',
    age: '20',
    gender: 'Male',
    car: 'Suzuki',
  },
  {
    id: '98',
    first_name: 'Noelyn',
    last_name: 'Fone',
    age: '20',
    gender: 'Female',
    car: 'Audi',
  },
  {
    id: '99',
    first_name: 'Malinda',
    last_name: 'Domange',
    age: '21',
    gender: 'Male',
    car: 'Saturn',
  },
  {
    id: '100',
    first_name: 'Kelli',
    last_name: 'Kmieciak',
    age: '21',
    gender: 'Male',
    car: 'Pontiac',
  },
];
